### ISSUE TITLE
Udp Connection Handling Problem

### ISSUE THREAD

**Issue by miladj** [bepass-org/proxy#8]
سلام و تشکر از زحماتتون

به نظر میاد تو socks وقتی درخواست برای udp میاد یه مشکل کوچیکی داره 

برای آدرس udp از مقدار destinationAddr استفاده شده
که به نظر میاد باید از مقدار nil یا "0.0.0.0:0" استفاده شود

تغییرات من اینجا دادم اگه لطف کنید این رو هم اعمال کنید ممنون میشم یا من pull request بزنم؟

https://github.com/bepass-org/proxy/commit/772d6026f2d001e7297edb2fb7a9dafa0e4ae11b

**Comment by uoosef** [comment]
سلام با تشکر لطفا pull بزنید
